name: Deployment staging
on:
  push:
    branches: staging

jobs:
  testdocker:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/setup-node@v3
      - run: ls -la
      - run: npm-v
