name:  Mon premier workflow
on: [push]

env:
  VAR_1: from workflow
  
jobs:
  say-hello:
    env:
      VAR_2: from job
    runs-on: ubuntu-latest
    steps:
      - name: hello
        env:
          VAR_3: from step
          VAR_1: var_1 from step
        run: |
          echo VAR_1: $VAR_1
          echo VAR_2: $VAR_2
          echo VAR_3: $VAR_3
          echo VAR_4: $VAR_4
          echo SECRET_1: $SECRET_1
          
          
      
