name: pull_request_flow
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo fruit=pomme >> $GITHUB_OUTPUT
        id: step1
      - run: echo ::error::fruit is ${{ steps.step1.outputs.fruit }} should be poire
        if: steps.step1.outputs.fruit != 'poire'
    
