name: pull_request_flow
on: push

jobs:
  testartifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo 123 > test.txt
      - uses: actions/upload-artifact@v4
        with:
          name: myfirstartifact
          path: ./test.txt

  downloadartifact:
    needs: testartifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: myfirstartifact
          path: ./here
      - run: |
          ls
          ls ./here
          cat ./here/test.txt
