name: pull_request_flow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        vers: [12, 13]
        exclude:
          - os: windows-latest
            vers: 12
    steps:
      - run: echo ${{ matrix.os }} ${{ matrix.vers }}
