name: pull_request_flow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install node.js
        uses: actions/setup-node@v4
      - name: fetch repository
        uses: action/checkout@v4
      - name: install depdendencies
        run: npm install
        working-directory: ./vite-project
