name: pull_request_flow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cloud: ovh
            endpoint: url1
          - cloud: aws
            endpoint: url2
    steps:
      - run: echo ${{ matrix.cloud }} ${{ matrix.endpoint }}
