name: pull_request_flow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install node.js
        uses: actions/setup-node@v4
      - name: fetch repository
        uses: actions/checkout@v4
      - name: configure cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('./vite-project/package-lock.json') }}
          path: ./vite-project/.npm

      - name: install depdendencies
        run: npm ci --cache .npm
        working-directory: ./vite-project
