name:  Mon premier workflow
on: 
  push:
    branches:
      - main
      - feature
    paths:
      - '**.png'
      - '!doc/**'
    #  paths-ignore:
     # - 'doc/**'
      
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo traitement image


