name: pull_request_flow
on: push

jobs:
  testdocker:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - run: npm -v
