name:  Mon premier workflow
on: 
  push:
    #  branches:
    #   - main
    #  - feature
    #  branches-ignore:
    # - main
    paths:
      - '**.png'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo traitement image


