name: pull_request_flow
on: push

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://test.fr
    steps:
      - run: |
          echo Deploy to producion
