name: pull_request_flow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: waitform
      cancel-in-progress: true
    steps:
      - run: |
          echo very long step
          sleep 100
          echo Done
