name: pull_request_flow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_STEP_SUMMARY
      - run: |
          echo '# Je suis un titre' >> $GITHUB_STEP_SUMMARY
          echo 'Je suis du contenu :rocket:' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '- un' >> $GITHUB_STEP_SUMMARY
          echo '- deux' >> $GITHUB_STEP_SUMMARY
          echo '- trois' >> $GITHUB_STEP_SUMMARY
