name: pull_request_flow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          titre=$TITLE
          echo Hello world!
        env:
          TITLE: ${{ github.event.head_commit.message}}
